check_palindrome:
    path: /check_palindrome/{input}
    controller: App\Controller\MainController::checkPalindrome

check_anagram:
    path: /check_anagram/{word}/{comparison}
    controller: App\Controller\MainController::checkAnagram

check_pangram:
    path: /check_pangram/{phrase}
    controller: App\Controller\MainController::checkPangram
